
#!/bin/sh

# macbuildRT.sh
# Builds RawTherapee on macOS 10.15.5 / Xcode 11.5
#
# Created by Richard Barber on 12/1/18.
#
# GIT DEPENDENCIES AND BUILD TOOLS
cd ~
git clone https://gitlab.gnome.org/GNOME/gtk.git
git clone git://anongit.freedesktop.org/git/cairo
git clone git://anongit.freedesktop.org/git/pixman.git
git clone https://gitlab.gnome.org/GNOME/pango.git
git clone https://gitlab.freedesktop.org/fontconfig/fontconfig.git
git clone https://git.savannah.gnu.org/git/freetype/freetype2.git
git clone https://github.com/harfbuzz/harfbuzz.git
git clone https://gitlab.gnome.org/GNOME/glib.git
git clone https://gitlab.gnome.org/GNOME/gtkmm.git
git clone https://gitlab.gnome.org/GNOME/gobject-introspection.git
git clone https://gitlab.gnome.org/GNOME/atk.git
git clone https://gitlab.gnome.org/GNOME/atkmm.git
git clone https://gitlab.gnome.org/GNOME/glibmm.git
git clone https://github.com/libsigcplusplus/libsigcplusplus.git
git clone git://git.code.sf.net/p/libpng/code libpng
git clone https://github.com/madler/zlib.git
git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git
git clone https://github.com/mm2/Little-CMS.git lcms
git clone https://github.com/libexpat/libexpat.git
git clone https://github.com/lensfun/lensfun.git
git clone https://github.com/svn2github/pcre.git
git clone https://github.com/anholt/libepoxy.git
git clone https://github.com/silnrsi/graphite.git
git clone git://github.com/libffi/libffi.git
git clone https://github.com/Kitware/CMake.git
git clone git://git.savannah.gnu.org/automake.git
git clone git://git.savannah.gnu.org/libtool.git
git clone git://anongit.freedesktop.org/pkg-config
git clone https://github.com/openssl/openssl
git clone https://github.com/ninja-build/ninja.git
git clone https://github.com/mesonbuild/meson.git
git clone https://github.com/doxygen/doxygen.git
git clone https://gitlab.gnome.org/GNOME/mm-common.git
git clone https://gitlab.gnome.org/GNOME/pangomm.git
git clone https://github.com/fribidi/fribidi.git
git clone https://github.com/freedesktop/cairomm.git
git clone https://gitlab.gnome.org/GNOME/gdk-pixbuf.git
git clone https://github.com/mdadams/jasper.git
git clone git://anongit.freedesktop.org/xorg/util/macros
git clone https://gitlab.gnome.org/GNOME/gtk-doc.git
git clone https://gitlab.gnome.org/GNOME/librsvg.git
git clone https://github.com/rust-lang/rust.git
git clone https://gitlab.gnome.org/GNOME/libcroco.git
git clone https://gitlab.gnome.org/GNOME/libxml2
git clone https://gitlab.gnome.org/GNOME/libxslt
git clone https://gitlab.gnome.org/GNOME/gtk-mac-integration.git
git clone https://github.com/llvm/llvm-project.git
git clone git://git.savannah.gnu.org/gnulib.git
git clone https://github.com/itstool/itstool.git
git clone https://gitlab.freedesktop.org/xdg/shared-mime-info.git
git clone https://git.savannah.gnu.org/git/bison.git
git clone https://github.com/Benitoite/rt-create-dmg.git
git clone git://git.sv.gnu.org/sed
git clone https://sourceware.org/git/bzip2.git
git clone https://pagure.io/xmlto.git
git clone https://github.com/pborman/getopt.git

# maccross file for cross compilation using macOS SDK, flags, etc
curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/maccross -o maccross

# libiptcdata
curl https://svwh.dl.sourceforge.net/project/libiptcdata/libiptcdata/1.0.4/libiptcdata-1.0.4.tar.gz -o iptcdata.tar.gz && gunzip -c iptcdata.tar.gz | tar xopf - && rm iptcdata.tar.gz

# fftw
curl http://fftw.org/fftw-3.3.8.tar.gz -o fftw.tar.gz && gunzip -c fftw.tar.gz | tar xopf - && rm fftw.tar.gz && mv fftw-3* fftw-3

# TIFF
curl http://download.osgeo.org/libtiff/tiff-4.1.0.zip -o tiff.zip && unzip tiff.zip -d tiff && rm tiff*zip

# wget
curl http://ftp.gnu.org/gnu/wget/wget-1.20.3.tar.gz -o wget.tar.gz && tar xf wget.tar.gz && rm wget*gz && mv wget-1* wget-1

# xz decompression enginge
curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/xz.zip -o xz.zip && unzip xz.zip && tar -xvf xz*tar && rm xz.zip && rm xz*tar

# libiconv
curl http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz -o libiconv.tar.gz && tar xf libiconv.tar.gz && rm libiconv*gz && mv libiconv-1* libiconv-1

# texinfo
curl https://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.xz -o texinfo.tar.xz && tar xf texinfo.tar.xz && rm tex*xz

# autoconf
curl -L http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz -o autoconf.gz && tar -xzf autoconf.gz && rm autoconf.gz && mv autoconf-2* autoconf-2

# autoconf-archive
curl http://mirror.csclub.uwaterloo.ca/gnu/autoconf-archive/autoconf-archive-2019.01.06.tar.xz -o autoconf-archive.tar.xz && tar xf autoconf-archive.tar.xz && rm auto*xz && mv autoconf-archive* autoconf-archive

# docbook
curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/docbook-xml.zip -o docbook-xml.zip && unzip docbook-xml.zip -d ./docbook-xml && rm doc*zip

# docbook-xslt10-stylesheets
curl https://github.com/docbook/xslt10-stylesheets/releases/download/release/1.79.2/docbook-xsl-1.79.2.tar.gz -L -o docbook-xsl.tar.gz && tar xvf docbook-xsl.tar.gz && rm docbook-xsl*gz

# util-macros
curl https://www.x.org/archive/individual/util/util-macros-1.19.1.tar.bz2 -o util-macros.tar.bz2 && tar xvjf util-macros.tar.bz2

# nasm
curl https://www.nasm.us/pub/nasm/releasebuilds/2.14.03rc2/macosx/nasm-2.14.03rc2-macosx.zip -o nasm.zip && unzip nasm.zip && rm nasm.zip && mv nasm* nasm && export PATH=~/nasm:$PATH

# adwaita icons
curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/adwaita.zip -o adwaita.zip && unzip adwaita.zip && rm adwaita.zip

# help2man
curl http://gnu.spinellicreations.com/help2man/help2man-1.47.11.tar.xz -o help2man.tar.xz && tar xf help2man.tar.xz && rm help2man*z

# autoconf-archive
curl https://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2019.01.06.tar.xz -o aa.tar.xz && tar xf aa.tar.xz && rm aa.tar.xz

# m4
curl https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz -o m4.tar.xz && tar xf m4.tar.xz && rm m4.tar.xz && mv m4-1.4.18 m4-code

# Python 3
curl https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz -o py.tar.xz && tar xf py.tar.xz && rm py.tar.xz

# glib-2
# curl -L https://ftp.gnome.org/pub/gnome/sources/glib/2.64/glib-2.64.2.tar.xz -o glib.xz && tar xf glib.xz && rm glib.xz && mv glib-2* glib-2

# PNG
curl -L https://download.sourceforge.net/libpng/libpng-1.6.37.tar.xz -o libpng.xz && tar xf libpng.xz && rm libpng.xz && mv libpng-1* libpng-1

# getopt
#curl -L http://frodo.looijaard.name/system/files/software/getopt/getopt-1.1.6.tar.gz -o getopt.gz && tar xf getopt.gz && rm getopt.gz && mv getopt-1* getopt-1

# xmlto
#curl -L https://releases.pagure.org/xmlto/xmlto-0.0.28.tar.bz2 -o xmlto.bz2 && tar xvjf xmlto.bz2 && rm xmlto.bz2 && mv xmlto-0* xmlto-0

# atk
curl -L https://download.gnome.org/sources/atk/2.36/atk-2.36.0.tar.xz -o atk.xz && tar xf atk.xz && rm atk.xz && mv atk-2* atk-2

# Build tools and libraries

cd ~/CMake && git pull && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install && export PATH=/opt/local/bin:$PATH

cd ~/autoconf-2 && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/autoconf-archive && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/automake && CC=clang CXX=clang++ ./bootstrap --prefix=/opt/local && ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/xz* && ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/Library && MACOSX_DEPLOYMENT_TARGET="10.9" LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" MACOSX_DEPLOYMENT_TARGET="10.9" make -j8 && sudo make install

sudo ln -s /opt /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk

cd ~/help2man* && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/libtool && CC=clang CXX=clang++ ./bootstrap && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/pkg-config && CC=clang CXX=clang++ sh ./autogen.sh --prefix=/opt/local --with-internal-glib && make -j8 && sudo make install

cd ~/openssl && CC=clang CXX=clang++ ./config --prefix=/opt/local && make -j8 && sudo make install

cd ~/wget-1 && ./bootstrap && CC=clang CXX=clang++ ./configure --prefix=/opt/local --disable-dependency-tracking --enable-assert --with-ssl=openssl && make -j8 && sudo make install

cd ~/m4-code && curl https://raw.githubusercontent.com/macports/macports-ports/edf0ee1e2cf/devel/m4/files/secure_snprintf.patch -o patch && patch -p0 < patch && ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/texinfo && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/gettext && git clean -dxf && LT_SYS_LIBRARY_PATH=/usr/lib CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ sh autogen.sh --with-libiconv-prefix=/usr/lib --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --enable-shared=yes --disable-dependency-tracking --disable-silent-rules --disable-debug gl_cv_func_ftello_works=yes --with-included-glib --with-included-libcroco --with-included-libunistring --disable-java --disable-csharp --without-git --without-cvs --without-xz && LT_SYS_LIBRARY_PATH=/usr/lib CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ ./configure --with-libiconv-prefix=/usr/lib --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --enable-shared=yes --disable-dependency-tracking --disable-silent-rules --disable-debug gl_cv_func_ftello_works=yes --with-included-glib --with-included-libcroco --with-included-libunistring --disable-java --disable-csharp --without-git --without-cvs --without-xz && LT_SYS_LIBRARY_PATH=/usr/lib make -j8 && sudo make install

cd ~/sed && ./bootstrap && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"  CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ ./configure --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && make -j8 && sudo make install

cd ~/doxygen && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DICONV_LIBRARY:FILEPATH=/opt/local/lib/libiconv.dylib -DPYTHON_EXECUTABLE=/usr/bin/python3 && curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/doxygen.patch | git apply && make -j8 && sudo make install

# cd ~/gettext && curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/gettext.patch | git apply && sh ./gitsub.sh pull && echo "AC_CONFIG_MACRO_DIRS([m4])" >> configure.ac && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"  CC=clang CXX=clang++ sh autogen.sh --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ ./configure --without-libiconv-prefix --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-dependency-tracking --disable-silent-rules --disable-debug gl_cv_func_ftello_works=yes --with-included-glib --with-included-libcroco --with-included-libunistring --disable-java --disable-csharp --without-git --without-cvs --without-xz && make -j8 && sudo make install

cd ~/pcre && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CPPFLAGS="-I/opt/local/include" sh ./autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --enable-utf8 --enable-pcre16 --enable-pcre32 --enable-unicode-properties && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CPPFLAGS="-I/opt/local/include" ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --enable-utf8 --enable-pcre16 --enable-pcre32 --enable-unicode-properties && make -j8 && sudo make install

cd ~/gettext && git clean -dxf && LT_SYS_LIBRARY_PATH=/usr/lib CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ sh autogen.sh --with-libiconv-prefix=/usr/lib --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --enable-shared=yes --disable-dependency-tracking --disable-silent-rules --disable-debug gl_cv_func_ftello_works=yes --with-included-glib --with-included-libcroco --with-included-libunistring --disable-java --disable-csharp --without-git --without-cvs --without-xz && LT_SYS_LIBRARY_PATH=/usr/lib CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"   CC=clang CXX=clang++ ./configure --with-libiconv-prefix=/usr/lib --with-included-gettext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk --enable-shared=yes --disable-dependency-tracking --disable-silent-rules --disable-debug gl_cv_func_ftello_works=yes --with-included-glib --with-included-libcroco --with-included-libunistring --disable-java --disable-csharp --without-git --without-cvs --without-xz && LT_SYS_LIBRARY_PATH=/usr/lib make -j8 && sudo make install

cd ~/bison && git clean -dxf && git pull && git submodule update --init && ./bootstrap && CC=clang CXX=clang++ ./configure --prefix=/opt/local && make -j8 && sudo make install

cd ~/ninja && python3 ./configure.py --bootstrap && ./ninja && chmod +x ninja && sudo cp ninja /opt/local/bin

cd ~/meson && ninja && chmod +x meson.py && sudo cp meson.py /opt/local/bin/meson

cd ~/libjpeg-turbo && git clean -dxf && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && make -j8 && sudo make install

cd ~/tiff/tiff* && mkdir _build && cd _build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && make -j8 && sudo make install

cd ~/zlib && git clean -dxf && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && make -j8 && sudo make install

cd ~/libpng-1 && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local -DZLIB_LIBRARY_RELEASE:FILEPATH=/opt/local/lib/libz.dylib && make -j8 && sudo make install

cd ~/libexpat/expat && git clean -dxf && mkdir build && cd build && DYLIB_CURRENT_VERSION=8.0.1 DYLIB_COMPATIBILITY_VERSION=7.0.0 CFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names,-undefined,dynamic_lookup,-compatibility_version,7.0.0,-current_version,8.0.1" cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && DYLIB_CURRENT_VERSION=8.0.1 CFLAGS="-mmacosx-version-min=10.9" DYLIB_COMPATIBILITY_VERSION=7.0.0 LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names,-undefined,dynamic_lookup,-compatibility_version,7.0.0,-current_version,8.0.1" make -j8 && CFLAGS="-mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names,-undefined,dynamic_lookup,-compatibility_version,7.0.0,-current_version,8.0.1" sudo make install



cd ~/libffi && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,." CPPFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" PYTHON=python3 PKG_CONFIG_PATH=/opt/local/lib/pkgconfig sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,." CPPFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" PYTHON=python3 PKG_CONFIG_PATH=/opt/local/lib/pkgconfig ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,." CPPFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" PYTHON=python3 PKG_CONFIG_PATH=/opt/local/lib/pkgconfig make -j8 && sudo make install

cd ~/fftw-3 && sh bootstrap.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk && make -j8 && sudo make install

cd ~/graphite && git clean -dxf && git checkout 1.3.14 && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local -DCMAKE_MACOSX_RPATH=/opt/local/lib -DCMAKE_SHARED_LINKER_FLAGS="-L /opt/local/lib -rpath /opt/local/lib" && make -j8 && sudo make install && sudo install_name_tool -id /opt/local/lib/libgraphite2.3.dylib /opt/local/lib/libgraphite2.3.2.1.dylib

cd ~/bzip2 && git clean -dxf && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install PREFIX=/opt/local && sudo ln -s /opt/local/lib/pkgconfig/bz2.pc /opt/local/lib/pkgconfig/bzip2.pc

cd ~/freetype2 && sudo ln -s /opt/local/bin/libtoolize /opt/local/bin/glibtoolize || sudo rm -f -r build && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local -DCMAKE_C_COMPILER="clang" -DCMAKE_EXE_LINKER_FLAGS="-arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" -DZLIB_LIBRARY_RELEASE=/opt/local/lib/libz.dylib -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" -DBUILD_SHARED_LIBS=ON && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" make -j8 && sudo make install

cd ~/fontconfig && git clean -dxf && sed -i -e 's+"libintl.h"+"/opt/local/include/libintl.h"+g' src/*.{c,h} && sed -i -e 's+<libintl.h>+"/opt/local/include/libintl.h"+g' src/*.{c,h} && autoreconf -vfi && EXPAT_LIBS=/opt/local/lib/libexpat.1.dylib LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib /opt/local/lib/libexpat.1.dylib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" FREETYPE_LIBS="$(pkg-config --libs freetype2) $(pkg-config --libs bz2)" FREETYPE_CFLAGS="$(pkg-config --cflags freetype2) $(pkg-config --cflags bz2)" ./configure --with-pkgconfigdir=/opt/local/lib/pkgconfig --with-libintl-prefix=/opt/local --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --enable-libxml2 &&  LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /opt/local/lib/libexpat.1.dylib -Wl,-rpath -Wl,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9"  make -j8 && sudo make install || sudo install_name_tool -change @rpath/libpng16.16.dylib /opt/local/lib/libpng16.16.dylib /Users/rb/fontconfig/fc-cache/.libs/fc-cache && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /Users/rb/fontconfig/fc-cache/.libs/fc-cache && install_name_tool -change @rpath/libexpat.1.dylib /opt/local/lib/libexpat.1.dylib /Users/rb/fontconfig/fc-cache/.libs/fc-cache && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /Users/rb/fontconfig/src/.libs/libfontconfig.1.dylib && sudo install_name_tool -change @rpath/libexpat.1.dylib /opt/local/lib/libexpat.1.dylib /Users/rb/fontconfig/src/.libs/libfontconfig.1.dylib && sudo install_name_tool -add_rpath /opt/local/lib /opt/local/lib/libfreetype.6.17.1.dylib && sudo make install
 
cd ~/libiptc* && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && make -j8 && sudo make install

cd ~/libiconv-1 && curl https://raw.githubusercontent.com/Homebrew/patches/9be2793af/libiconv/patch-utf8mac.diff | git apply   && echo "#define ei_utf8mac_oflags (HAVE_ACCENTS | HAVE_QUOTATION_MARKS | HAVE_HANGUL_JAMO)" >> lib/flags.h && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --disable-static && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --disable-static && curl https://raw.githubusercontent.com/Beep6581/RawTherapee/dev/tools/osx/libiconv_1.16_rt.patch -o libiconv_1.16_rt.patch && patch -p1 < libiconv_1.16_rt.patch && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install && libtool --finish /opt/local/lib

cd ~/gnulib && true

#cd ~/glib && git checkout 2.59.3 && LIBRARY_PATH='/opt/local/lib' LD=ld CC=clang CXX=clang++ CFLAGS="-O3 -mtune=generic -v -std=c11 -fstrict-aliasing -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /opt/local/lib/libintl.8.dylib -v -bind_at_load -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-O3 -mtune=generic -std=c++11 -I/opt/local/include -arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --with-harfbuzz=no --enable-shared=yes && LIBRARY_PATH='/opt/local/lib' LD=ld CC=clang CXX=clang++ CFLAGS="-O3 -mtune=generic -v -std=c11 -fstrict-aliasing -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /opt/local/lib/libintl.8.dylib -v -bind_at_load -arch x86_64 -mmacosx-version-min=10.9 -L /opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-O3 -mtune=generic -std=c++11 -I/opt/local/include -arch x86_64 -mmacosx-version-min=10.9" make -j8 || LIBRARY_PATH='/opt/local/lib' LD=ld CC=clang CXX=clang++ CFLAGS="-O3 -mtune=generic -v -std=c11 -fstrict-aliasing -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /opt/local/lib/libintl.8.dylib -v -bind_at_load -arch x86_64 -mmacosx-version-min=10.9 -L /opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-O3 -mtune=generic -std=c++11 -I/opt/local/include -arch x86_64 -mmacosx-version-min=10.9" make && sudo make install && sudo mv /opt/local/lib/libglib-2.0.la glib.la && sudo make uninstall && make clean

cd ~/glib && git checkout 2.59.3 && curl https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1450.patch | git apply && echo "#define _GNU_SOURCE" > glib/glib-unix.c && meson setup --pkg-config-path /opt/local/lib --cmake-prefix-path /opt/local --prefix=/opt/local --buildtype=release _build . -D iconv=external --cross-file ~/maccross --optimization 3 --default-library=shared -D installed_tests=false -D dtrace=false -D bsymbolic_functions=false -D gio_module_dir=/opt/local/lib/gio/modules -D force_posix_threads=true && ninja -C _build && sudo ninja install -C _build && sudo install_name_tool -change libz.1.dylib /opt/local/lib/libz.1.dylib /opt/local/lib/libgio-2.0.0.dylib && sed -i -e "s+5900+$(otool -l /opt/local/lib/libglib-2.0.dylib | grep "current version" | head -1 | tail -c9 | cut -c1-4)+g" glib.la && sudo cp glib.la /opt/local/lib/libglib-2.0.la

cd ~/lensfun && sudo git clean -dxf && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && make -j8 && sudo make install

cd ~/lcms && git clean -dxf && sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes 'CFLAGS=-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include' 'LDFLAGS=-arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib' CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CPPFLAGS="-I/opt/local/include" && make -j8 && sudo make install

cd ~/pixman && git clean -dxf && sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes 'CFLAGS=-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include' 'LDFLAGS=-arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib' CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CPPFLAGS="-I/opt/local/include" && make -j8 && sudo make install

cd ~/cairo && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --enable-quartz-image --enable-quartz-font --enable-quartz --enable-ft --disable-xlib --without-x &&  CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --enable-quartz-image --enable-quartz-font --enable-quartz --enable-ft --disable-xlib --without-x && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install && sudo install_name_tool -add_rpath /opt/local/lib /opt/local/lib/libcairo.2.dylib && sudo install_name_tool -change libfreetype.6.dylib @rpath/libfreetype.6.dylib /opt/local/lib/libcairo.2.dylib && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /opt/local/lib/libcairo-gobject.2.dylib

cd ~/mm-common && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-documentation && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/libxml2 && git pull && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --disable-silent-rules --with-python --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install && sudo install_name_tool -change libz.1.dylib /opt/local/lib/libz.1.dylib /opt/local/lib/libxml2.2.dylib

#cd ~/itstool && PYTHON=python sh autogen.sh --prefix=/opt/local && make -j8 && sudo make install

#cd ~/getopt-1 && make && sudo make install

#cd ~/xmlto-0 && curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/xmlto.patch -o xmlto.patch && patch -p0 xmlto.in < xmlto.patch && autoreconf -vfi && ./configure --disable-dependency-tracking --prefix=/opt/local && make && sudo make install

#cd ~/shared-mime-info && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-documentation && cd ~/shared-mime-info && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-documentation && make -j8 && sudo make install make -j8 && sudo make install

cd ~/shared-mime-info && XML_CATALOG_FILES=/usr/local/etc/xml/catalog LIBRARY_PATH="/opt/local/lib" CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" meson _build -Ddocs=false --prefix=/opt/local --buildtype release --default-library both --optimization 3 --cross-file ~/maccross && XML_CATALOG_FILES=/opt/local/etc/xml/catalog LIBRARY_PATH="/opt/local/lib" CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ninja -C _build && sudo ninja -C _build install

cd ~/libsigcplusplus && git checkout 3.0.3 && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-documentation && LIBRARY_PATH="/opt/local/lib" LD=ld CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/autoconf-archive && ./configure --prefix=/opt/local && make && sudo make install

cd ~/gobject-introspection && ln -s -f /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/*.h /opt/local/include && git pull && PYTHON=python3 CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-rpath -Wl,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" meson setup _build . --prefix=/opt/local -D python=python3 -D doctool=disabled --buildtype release --default-library both --optimization 3 --cross-file ~/maccross && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" ninja -C _build && sudo ninja -C _build install

cd ~/atk && git clean -dxf && git checkout master && CC=clang CXX=clang++ CFLAGS="-Wl,-rpath,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-Wl,-rpath -Wl,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" meson setup _build . --prefix=/opt/local --cross-file ~/maccross -D introspection=false && ninja -C _build && sed -i -e 's/-current_version=1/-current_version 1/g' _build/build.ninja && sed -i -e 's/-compatibility_version=1/-compatibility_version 1/g' _build/build.ninja && CC=clang CXX=clang++ CFLAGS="-Wl,-rpath,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-Wl,-rpath -Wl,/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" ninja -C _build && sudo ninja -C _build install

cd ~/glibmm && git clean -dxf && git checkout master && CC=clang CXX=clang++ sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes CFLAGS="-mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -std=c++17" && CFLAGS="-mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CXXFLAGS="-mtune=generic -arch x86_64 -mmacosx-version-min=10.9 -std=c++17" make -j8 && sudo make install

cd ~/atkmm && git clean -dxf && git checkout 2.24.3 && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" CC=clang CXX=clang++ make -j8 && sudo make install

cd ~/harfbuzz && git checkout master && autoreconf -vfi && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure  --with-coretext --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --with-glib=yes --with-graphite2=yes && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /opt/local/lib/libharfbuzz.0.dylib && sudo install_name_tool -change libgraphite2.3.dylib /opt/local/lib/libgraphite2.3.dylib /opt/local/lib/libharfbuzz.0.dylib

cd ~/fribidi && git checkout master && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" meson setup _build -Ddocs=false --prefix=/opt/local --buildtype release --default-library both --optimization 3 --cross-file ~/maccross && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ninja -C _build && sudo ninja -C _build install

cd ~/pango && git checkout master && meson wrap promote subprojects/glib/subprojects/proxy-libintl.wrap && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" meson setup --prefix=/opt/local --sysconfdir=/etc --buildtype release --default-library both --optimization 3 --cross-file ~/maccross _build . && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ninja -C _build && sudo ninja install -C _build && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /opt/local/lib/libpangocairo-1.0.0.dylib && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib /opt/local/lib/libpangoft2-1.0.0.dylib

cd ~/cairomm && git checkout master && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes --disable-documentation && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/pangomm && git checkout master && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/libcroco && git pull && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --disable-Bsymbolic && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/libxslt && git pull && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~ && curl http://www.oasis-open.org/docbook/xml/4.2/docbook-xml-4.2.zip -o docbook-xml-4.2.zip && sudo mkdir -p /usr/local/share/docbook-xml-4.2 && cd /usr/local/share/docbook-xml-4.2 && sudo unzip ~/docbook-xml-4.2 && cd ~ && curl http://downloads.sourceforge.net/docbook/docbook-xsl-1.73.2.tar.bz2 -L -o docbookxsl.tar.bz2 && cd /usr/local/share && sudo tar xjvf ~/docbookxsl.tar.bz2 && rm ~/docbookxsl.tar.bz2 && export XML_CATALOG_FILES="/usr/local/share/docbook-xsl-1.73.2/catalog /usr/local/share/docbook-xml-4.2/catalog"

cd ~/docbook-xml && curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/docbook-script1.sh -o docbook-script1.sh && sudo sh docbook-script1.sh

cd ~/docbook-xsl* && curl http://www.linuxfromscratch.org/patches/blfs/svn/docbook-xsl-nons-1.79.2-stack_fix-1.patch -o patch1.patch && patch -Np1 -i patch1.patch || sudo install -v -m755 -d /usr/local/share/xml/docbook/xsl-stylesheets-1.79.2 && sudo cp -v -R VERSION assembly common eclipse epub epub3 extensions fo highlighting html htmlhelp images javahelp lib manpages params profiling roundtrip slides template tests tools webhelp website xhtml xhtml-1_1 xhtml5 /usr/local/share/xml/docbook/xsl-stylesheets-1.79.2 && sudo ln -s VERSION /usr/local/share/xml/docbook/xsl-stylesheets-1.79.2/VERSION.xsl && sudo install -v -m644 README /usr/local/share/doc/docbook-xsl-1.79.2/README.txt && sudo install -v -m644 RELEASE-NOTES* NEWS* /usr/local/share/doc/docbook-xsl-1.79.2 && curl https://raw.githubusercontent.com/Benitoite/RTdeps/master/xslconfig.sh -o xslconfig.sh && sudo sh xslconfig.sh && install -d /usr/local/share/xml/docbook-xsl/1.79.2/docbook-xsl && sudo install catalog.xml /usr/local/share/xml/docbook-xsl/1.79.2/docbook-xsl/catalog.xml

cd ~/macros && git pull && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-shared=yes && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/libepoxy && git clean -dxf && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" meson _build -Ddocs=false --prefix=/opt/local --buildtype release --default-library both --optimization 3 --cross-file ~/maccross && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ninja -C _build && sudo ninja -C _build install

cd ~/jasper && git clean -dxf && mkdir _build && cd _build && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/gdk-pixbuf && git clean -dxf && git checkout 2.40.0 && CC=clang CXX=clang++ CFLAGS="-I/opt/local/include/libpng16 -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath,/Applications/RawTherapee.app/Contents/Frameworks" CXXFLAGS="-I/opt/local/include/libpng16 -Dx11=false -D_REENTRANT -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" meson _build -Dnative_windows_loaders=false -Drelocatable=true -Dgir=true -Dx11=false -Dman=false --prefix=/opt/local -D installed_tests=false -D gir=true -D png=true -Ddocs=false -Dman=false --prefix=/opt/local --buildtype release --default-library shared --optimization 3 --cross-file ~/maccross && cd _build && CC=clang CXX=clang++ CFLAGS="-I/opt/local/include/libpng16 -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath,/opt/local/lib" CXXFLAGS="-D_REENTRANT -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include -I/opt/local/include/libpng16" ninja && sudo ninja install && sudo install_name_tool -add_rpath /opt/local/lib /opt/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so && sudo install_name_tool -add_rpath /opt/local/lib /opt/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so && sudo install_name_tool -add_rpath /opt/local/lib /opt/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so

cd ~/gtk && git clean -dxf && git checkout 3.24.20 && CC=clang CXX=clang++ CXXFLAGS="-DX_LOCALE" CFLAGS="-fstrict-aliasing" meson setup --prefix=/opt/local --buildtype=release _build . --cross-file ~/maccross --optimization 3 -D tests=false -D win32_backend=false -D wayland_backend=false -D x11_backend=false -D quartz_backend=true -D print_backends=file -D demos=false -D examples=false -D installed_tests=false -D builtin_immodules=yes -D introspection=false && ln -s /opt/local/lib _build/lib && V=1 CPP_FOR_BUILD=clang++ CC=clang CXX=clang++ CXXFLAGS="-DX_LOCALE" CFLAGS="-fstrict-aliasing" ninja -C _build && sudo install_name_tool -change libfreetype.6.dylib /opt/local/lib/libfreetype.6.dylib _build/gtk/libgtk-3.0.dylib && sudo ninja install -C _build

cd ~/gtkmm && git clean -dxf && git checkout 3.24.2 && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-std=c++11 -arch x86_64 -mmacosx-version-min=10.9" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --disable-documentation --enable-man=no --enable-quartz-backend=yes --enable-x11-backend=no --enable-broadway-backend=no --enable-win32-backend=no --enable-shared --enable-wayland-backend=no --libdir=/opt/local/lib && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~ && curl https://sh.rustup.rs -sSf | sh && rustup update

cd ~/librsvg && git clean -dxf && git checkout master && git pull && ln -s /opt/local/lib/libz.1.dylib ./libz.1.dylib && sudo install_name_tool -change libz.1.dylib @rpath/libz.1.dylib /opt/local/lib/libpng16.16.dylib && PKG_CONFIG_PATH=/opt/local/lib/pkgconfig'' CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -L/opt/local/lib -arch x86_64 -mmacosx-version-min=10.9 -Wl,-rpath -Wl,/Applications/RawTherapee.app/Contents/Frameworks" sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-introspection=no --enable-debug=no --enable-gtk-doc=no --disable-Bsymbolic --disable-tools --enable-static --enable-shared --disable-silent-rules --with-libiconv-prefix=/opt/local/lib --with-libintl-prefix=/opt/local/lib && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-headerpad_max_install_names -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" make -j8 && sudo make install

cd ~/nasm* && sudo install ldrdf nasm ndisasm rdf* rdx /opt/local/bin

cd ~/fftw-3 && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" ./configure --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --enable-debug=no --disable-fortran --enable-avx2 --enable-float --enable-avx --enable-sse --enable-sse2 --enable-threads && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib" CXXFLAGS="-arch x86_64 -mmacosx-version-min=10.9" make -j8 && sudo make install

cd ~/gtk-mac-integration && git clean -dxf && git checkout gtk-mac-integration-2.1.3 && CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" PKG_CONFIG_PATH=/opt/local/lib/pkgconfig CPPFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" PYTHON=python3 CC=clang CXX=clang++ LT_SYS_LIBRARY_PATH=/opt/local/lib sh autogen.sh --prefix=/opt/local --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk --libdir=/opt/local/lib --disable-glibtest --enable-introspection=no --enable-python=no --with-gtk3 --with-libiconv-prefix=/opt/local/lib --with-libintl-prefix=/opt/local/lib && sed -i -e 's/GETTEXT_MACRO_VERSION\ =\ 0.19/GETTEXT_MACRO_VERSION\ =\ 0.20/g' po/Makefile.in.in && CC=clang CXX=clang++ CFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" LDFLAGS="-Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -mmacosx-version-min=10.9 -L/opt/local/lib -Wl,-rpath -Wl,/opt/local/lib" CPPFLAGS="-arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/include" PYTHON=python3 PKG_CONFIG_PATH=/opt/local/lib/pkgconfig LT_SYS_LIBRARY_PATH=/opt/local/lib make -j8 && sudo make install

cd ~ && sudo ditto Adwaita /opt/local/share/icons/Adwaita

cd ~/llvm-project/openmp && git clean -dxf && mkdir build && cd build && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/opt/local -DCMAKE_MACOSX_RPATH=/opt/local/lib -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-headerpad_max_install_names -L /opt/local/lib -Wl,-rpath -Wl,/opt/local/lib"  -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" && make -j8 && sudo make install

cd ~/rt-create-dmg && chmod 4755 create-dmg && sudo ln -s ~/rt-create-dmg/create-dmg /opt/local/bin

# RawTherapee

cd ~ && git clone https://github.com/Beep6581/RawTherapee.git repo-rt && cd ~/repo-rt && sudo rm -r build || git checkout dev && git pull && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE="release" -DPROC_TARGET_NUMBER="1" -DPROC_LABEL="generic processor" -DCACHE_NAME_SUFFIX="5-dev" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_LTO="ON" -DCMAKE_OSX_SYSROOT="/" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.9" -DLOCAL_PREFIX:STRING="/opt" -DLENSFUNDBDIR="share/lensfun" -DCODESIGNID:STRING="Developer ID Application: Xxxxx Xxxxx (ABCDEFGHIJ)" -DNOTARY:STRING="--username aaaa@aaaa.aaaa --password abcd-efgh-hijk-lmno" -DCMAKE_CXX_FLAGS="-Wno-pass-failed -arch x86_64 -Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11" -DCMAKE_C_FLAGS="-Wno-pass-failed -arch x86_64 -Wno-deprecated-register -Wno-unused-command-line-argument" -DCMAKE_EXE_LINKER_FLAGS="--arch x86_64" -DOpenMP_C_FLAGS=-fopenmp=lomp -DOpenMP_CXX_FLAGS=-fopenmp=lomp -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_libomp_LIBRARY="/opt/local/lib/libomp.dylib" -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include" -DOpenMP_CXX_LIB_NAMES="libomp" -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DFANCY_DMG:BOOL=ON .. && make -j8 install && sudo make macosx_bundle

echo "-end of script-"
